services:
  ahtrieb:
    build:
      context: ../../ahtrieb.ch
      dockerfile: ../andromedalab-config/ahtrieb.ch/Dockerfile
    container_name: ahtrieb
    labels:
      traefik.enable: true
      traefik.http.routers.ahtrieb.rule: Host(`ahtrieb.ch`)
      traefik.http.routers.ahtrieb.tls: true
      traefik.http.routers.ahtrieb.tls.certresolver: letsencrypt
    networks:
      - ahtrieb

networks:
  ahtrieb:
    name: ahtrieb
    external: true