services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt 
    networks:
      - node
      - yniederer
      - alpina
      - jellyfin
      - jellyseerr
      - radarr
      - qbittorrent
      - prowlarr
      - sonarr
      - nextcloud
      - immich
networks:
  node:
    name: node
  yniederer:
    name: yniederer
  alpina:
    name: alpina
  jellyfin:
    name: jellyfin
  jellyseerr:
    name: jellyseerr
  radarr:
    name: radarr
  qbittorrent:
    name: qbittorrent
  prowlarr:
    name: prowlarr
  sonarr:
    name: sonarr
  nextcloud:
    name: nextcloud
  immich:
    name: immich
