services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - node
      - yniederer
networks:
  node:
    name: node
  yniederer:
    name: yniederer