services:
  tuwunel:
    image: jevolk/tuwunel:latest
    container_name: tuwunel
    volumes:
      - ../../data/tuwunel:/var/lib/tuwunel
    environment:
      TUWUNEL_DATABASE_PATH: /var/lib/tuwunel
      TUWUNEL_ADDRESS: 0.0.0.0
      TUWUNEL_SERVER_NAME: yniederer.ch
    labels:
      traefik.enable: true
      traefik.http.routers.tuwunel.rule: Host(`matrix.yniederer.ch`)
      traefik.http.routers.tuwunel.tls: true
      traefik.http.routers.tuwunel.tls.certresolver: letsencrypt
    networks:
      - tuwunel

networks:
  tuwunel:
    name: tuwunel
    external: true
