services:
  nextclouddb:
    image: mariadb:lts
    container_name: nextclouddb
    volumes:
      - ../../data/nextcloud/database:/media/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextclouddb
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MARIADB_DATABASE: nextclouddb
      MARIADB_USER: nextcloud
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - local

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - local

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - ../../data/nextcloud/html:/var/www/html
    environment:
      MYSQL_DATABASE: nextclouddb
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_HOST: nextclouddb
      REDIS_HOST: redis
      TRUSTED_PROXIES: 0.0.0.0/0
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.yniederer.ch
    depends_on:
      - nextclouddb
      - redis
    networks:
      - local
      - nextcloud
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.yniederer.ch`)
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: letsencrypt
      traefik.docker.network: nextcloud

networks:
  nextcloud:
   name: nextcloud
   external: true
  local:
