services:
  yniederer:
    build:
      context: ../../yniederer.ch
      dockerfile: ../andromedalab-config/yniederer.ch/Dockerfile
    container_name: yniederer
    labels:
      traefik.enable: true
      traefik.http.routers.yniederer.rule: Host(`yniederer.ch`)
      traefik.http.routers.yniederer.tls: true
      traefik.http.routers.yniederer.tls.certresolver: letsencrypt
    networks:
      - yniederer
networks:
  yniederer:
    name: yniederer
    external: true