services:
  node:
    build: .
    container_name: node
    labels:
      traefik.enable: true
      traefik.http.routers.node.rule: Host(`node.yniederer.ch`)
    networks:
      - node

networks:
  node:
    name: node
    external: true