services:
  node:
    build: .
    ports:
      - '3000:3000'
    container_name: node
    environment:
      - PORT=3000
    networks:
      - nodetest
networks:
  nodetest:
    name: nodetest
    external: true