services:
  alpina:
    image: nginx:alpine
    container_name: alpina
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets/:/usr/share/nginx/html/assets/:ro
    env_file: ".env"
    labels:
      traefik.enable: true
      traefik.http.routers.alpina.rule: Host(`${DOMAIN}`)
      traefik.http.routers.alpina.tls: true
      traefik.http.routers.alpina.tls.certresolver: letsencrypt
    networks:
      - alpina
networks:
  alpina:
    name: alpina
    external: true   
