services:
 minecraft:
   image: itzg/minecraft-server
   ports:
     - "25565:25565"
   environment:
     EULA: "TRUE"
     #CF_API_KEY: redacted to avoid stalking xD
     #CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10
     TYPE: AUTO_CURSEFORGE
     WHITE_LIST: "true"
   deploy:
     resources:
       limits:
         memory: 4G
   volumes:
     - "./minecraft_data:/data"
